version: "2.4"
services:
    discord_bot:
        build:
            context: .
            dockerfile: Docker/Dockerfile
        mem_limit: 128m
        cpus: 1.00
        restart: on-failure
        volumes:
            - .env:/bot/.env 
